SELECT  BCC,CENTERCODE,CENTERNAME FROM center_details WHERE BCC="VISAKHAPATNAM";
SELECT  BCC,CENTERCODE,CENTERNAME,BANKNAME,BANKLOCATION,JOINTACCOUNTNUMBER FROM center_details WHERE BCC="VISAKHAPATNAM";
SELECT  BCC,CENTERCODE,CENTERNAME,PS,HELPER1,HELPER2,HELPER3 FROM center_details WHERE BCC="VISAKHAPATNAM";
SELECT  BCC,CENTERCODE,CENTERNAME, EQUIPMENTDETAILS FROM center_details WHERE BCC="VISAKHAPATNAM";
SELECT * FROM center_details WHERE BCC="VISAKHAPATNAM";
SELECT * FROM center_details;


/*************************************************************/
SELECT BCC,BCC_BM_AVERAGE,BCC_CM_AVERAGE,BCC_TOTAL_AVERAGE,BCC_ENTRYMONTH,BCC_ENTRYDATE FROM bcc_procuriment WHERE BCC_ENTRYDATE="1/3/2017";
SELECT SUM(BCC_BM_AVERAGE)TOTAL_BM_AVERAGE FROM bcc_procuriment WHERE BCC_ENTRYDATE="1/3/2017";
SELECT SUM(BCC_CM_AVERAGE)TOTAL_CM_AVERAGE FROM bcc_procuriment WHERE BCC_ENTRYDATE="1/3/2017";
SELECT SUM(BCC_TOTAL_AVERAGE)TOTAL_AVERAGE FROM bcc_procuriment WHERE BCC_ENTRYDATE="1/3/2017";

SELECT BCC,BCC_BM_AVERAGE,BCC_CM_AVERAGE,BCC_TOTAL_AVERAGE,BCC_ENTRYMONTH,BCC_ENTRYDATE FROM bcc_procuriment WHERE BCC="VISAKHAPATNAM" AND BCC_ENTRYMONTH="MARCH";
SELECT SUM(BCC_BM_AVERAGE)TOTAL_BM_AVERAGE FROM bcc_procuriment WHERE BCC="VISAKHAPATNAM" AND BCC_ENTRYMONTH="MARCH";
SELECT SUM(BCC_CM_AVERAGE)TOTAL_CM_AVERAGE FROM bcc_procuriment WHERE BCC="VISAKHAPATNAM" AND BCC_ENTRYMONTH="MARCH";
SELECT SUM(BCC_TOTAL_AVERAGE)TOTAL_AVERAGE FROM bcc_procuriment WHERE BCC="VISAKHAPATNAM" AND BCC_ENTRYMONTH="MARCH";
**************************************************************************************************************
SELECT * FROM cattle_i WHERE CI_DATE_OF_ENTRY="2/5/2017";
SELECT SUM(CI_BUFFALOS)TOTAL_BUFFALOS FROM cattle_i WHERE CI_DATE_OF_ENTRY="2/5/2017";
SELECT SUM(CI_COWS)TOTAL_COWS FROM cattle_i WHERE CI_DATE_OF_ENTRY="2/5/2017";
SELECT SUM(CI_TOTALPREMIUM)TOTAL_PREMIUM FROM cattle_i WHERE CI_DATE_OF_ENTRY="2/5/2017";
SELECT SUM(CI_DDAMOUNT)TOTAL_AMOUNT FROM cattle_i WHERE CI_DATE_OF_ENTRY="2/5/2017";

SELECT * FROM cattle_i WHERE BCC="VISAKHAPATNAM" AND CI_DDMONTH="MARCH";
SELECT SUM(CI_BUFFALOS)TOTAL_BUFFALOS FROM cattle_i  WHERE BCC="VISAKHAPATNAM" AND CI_DDMONTH="MARCH";
SELECT SUM(CI_COWS)TOTAL_COWS FROM cattle_i WHERE BCC="VISAKHAPATNAM" AND CI_DDMONTH="MARCH";
SELECT SUM(CI_TOTALPREMIUM)TOTAL_PREMIUM FROM cattle_i WHERE BCC="VISAKHAPATNAM" AND CI_DDMONTH="MARCH";
SELECT SUM(CI_DDAMOUNT)TOTAL_AMOUNT FROM cattle_i WHERE BCC="VISAKHAPATNAM" AND CI_DDMONTH="MARCH";
/**************************************************************************************************************
SELECT * FROM claim_i WHERE CL_DATE_OF_ENTRY="1/3/2017";
SELECT SUM(CL_BUFFALOS)TOTAL_BUFFALOS FROM claim_i WHERE CL_DATE_OF_ENTRY="1/3/2017";
SELECT SUM(CL_COWS)TOTAL_COWS FROM claim_i WHERE CL_DATE_OF_ENTRY="1/3/2017";
SELECT SUM(CI_AMOUNT)TOTAL_AMOUNT FROM claim_i WHERE CL_DATE_OF_ENTRY="1/3/2017";


SELECT * FROM claim_i WHERE BCC="VISAKHAPATNAM" AND CL_ENTRYMONTH="MARCH";
SELECT SUM(CL_BUFFALOS)TOTAL_BUFFALOS FROM claim_i  WHERE BCC="VISAKHAPATNAM" AND CL_ENTRYMONTH="MARCH";
SELECT SUM(CL_COWS)TOTAL_COWS FROM claim_i WHERE BCC="VISAKHAPATNAM" AND CL_ENTRYMONTH="MARCH";
SELECT SUM(CI_AMOUNT)TOTAL_AMOUNT FROM claim_i WHERE BCC="VISAKHAPATNAM" AND CL_ENTRYMONTH="MARCH";
/**********************************************************************************************************************

SELECT * FROM sukhclaim_i WHERE SUCL_DATE_OF_ENTRY="1/3/2017";
SELECT COUNT(*)NO_OF_DEATHMEMBERS FROM sukhclaim_i WHERE SUCL_DATE_OF_ENTRY="1/3/2017";
SELECT SUM(SUCI_AMOUNT)TOTAL_AMOUNT FROM sukhclaim_i WHERE SUCL_DATE_OF_ENTRY="1/3/2017";


SELECT * FROM sukhclaim_i WHERE BCC="VISAKHAPATNAM" AND SUCL_ENTRYMONTH="MARCH";
SELECT COUNT(*)NO_OF_DEATHMEMBERS FROM sukhclaim_i  WHERE BCC="VISAKHAPATNAM" AND SUCL_ENTRYMONTH="MARCH";
SELECT SUM(SUCI_AMOUNT)TOTAL_AMOUNT FROM sukhclaim_i WHERE BCC="VISAKHAPATNAM" AND SUCL_ENTRYMONTH="MARCH";

SELECT SUM(SB_CARDS_AMOUNT)TOTAL_AMOUNT FROM cards WHERE BCC="VISAKHAPATNAM";
SELECT SUM(SUCI_AMOUNT)TOTAL_AMOUNT FROM sukhclaim_i WHERE BCC="VISAKHAPATNAM";

SELECT SUM(O.SB_CARDS_AMOUNT)-SUM(P.SUCI_AMOUNT)TOTAL_AMOUNT FROM cards O,sukhclaim_i P WHERE O.BCC=P.BCC="VISAKHAPATNAM";
///*************************************************************************************************************************

SELECT * FROM cards WHERE BCC="VISAKHAPATNAM";

SELECT SUM(NUMBER_OF_SB_CARDS)TOTAL_CARDS FROM cards WHERE BCC="VISAKHAPATNAM";
SELECT SUM(AABY_INSURANCE_HOLDERS)TOTAL_AABY FROM cards WHERE BCC="VISAKHAPATNAM";
SELECT SUM(TOTAL_CARDS)TOTAL_BOTH FROM cards WHERE BCC="VISAKHAPATNAM";

SELECT SUM(SB_CARDS_AMOUNT)TOTAL_CARDS_AMOUNT FROM cards WHERE BCC="VISAKHAPATNAM";
SELECT SUM(AABY_AMOUNT)TOTAL_AABY_AMOUNT FROM cards WHERE BCC="VISAKHAPATNAM";
SELECT SUM(TOTAL_AMOUNT)TOTAL_AMOUNT FROM cards WHERE BCC="VISAKHAPATNAM";

//******************************************************************************************
SELECT BCC,CENTERCODE,CENTERNAME,MPI_MPAC,PRESIDENT_GROUPMEMBER,PRESIDENT_NAME,PRESIDENT_TERM FROM commitee WHERE BCC="VISAKHAPATNAM";
SELECT BCC,CENTERCODE,CENTERNAME,MPI_MPAC,PRESIDENT_GROUPMEMBER,PRESIDENT_NAME,PRESIDENT_TERM FROM commitee WHERE PRESIDENT_TERM="1/3/2017" ORDER BY BCC;
SELECT * FROM commitee WHERE CENTERNAME="KOVVADA";
SELECT*FROM commitee WHERE BCC="VISAKHAPATNAM";
SELECT BCC,CENTERCODE,CENTERNAME,MPI_MPAC,PRESIDENT_GROUPMEMBER,PRESIDENT_NAME,PRESIDENT_TERM FROM commitee ORDER BY BCC;

SELECT BCC,CENTERCODE,CENTERNAME,DIRECTOR_NAMES,DIRECTOR_TERMS FROM directors WHERE BCC="VISAKHAPATNAM";
SELECT BCC,CENTERCODE,CENTERNAME,DIRECTOR_NAMES,DIRECTOR_TERMS FROM directors WHERE DIRECTOR_TERMS="1/3/2017" ORDER BY BCC;
SELECT BCC,CENTERCODE,CENTERNAME,DIRECTOR_NAMES,DIRECTOR_TERMS FROM directors ORDER BY BCC;

//**********************************************************************************************
SELECT A.BCC,A.CENTERCODE,A.CENTERNAME,A.A_BM_AVERAGE,A.A_CM_AVERAGE,A.A_TOTAL_AVERAGE,
B.M_BM_AVERAGE,B.M_CM_AVERAGE,B.M_TOTAL_AVERAGE,
C.JU_BM_AVERAGE,C.JU_CM_AVERAGE,C.JU_TOTAL_AVERAGE,
D.JUL_BM_AVERAGE,D.JUL_CM_AVERAGE,D.JUL_TOTAL_AVERAGE,
E.AU_BM_AVERAGE,E.AU_CM_AVERAGE,E.AU_TOTAL_AVERAGE,
F.S_BM_AVERAGE,F.S_CM_AVERAGE,F.S_TOTAL_AVERAGE,
G.O_BM_AVERAGE,G.O_CM_AVERAGE,G.O_TOTAL_AVERAGE,
H.N_BM_AVERAGE,H.N_CM_AVERAGE,H.N_TOTAL_AVERAGE,
I.D_BM_AVERAGE,I.D_CM_AVERAGE,I.D_TOTAL_AVERAGE,
J.JAN_BM_AVERAGE,J.JAN_CM_AVERAGE,J.JAN_TOTAL_AVERAGE,
K.F_BM_AVERAGE,K.F_CM_AVERAGE,K.F_TOTAL_AVERAGE,
L.MAR_BM_AVERAGE,L.MAR_CM_AVERAGE,L.MAR_TOTAL_AVERAGE
FROM 
a_procuriment A,m_procuriment B,ju_procuriment C,jul_procuriment D,
au_procuriment E,s_procuriment F,o_procuriment G,n_procuriment H,
d_procuriment I,jan_procuriment J,f_procuriment K,mar_procuriment L
WHERE
A.BCC= B.BCC= C.BCC= D.BCC= E.BCC= F.BCC= G.BCC= H.BCC= I.BCC= J.BCC= K.BCC=L.BCC="VISAKHAPATNAM";
//*************************************************************************************************************//
SELECT A.BCC,A.CENTERCODE,A.CENTERNAME,A.A_BM_AVERAGE,A.A_CM_AVERAGE,A.A_TOTAL_AVERAGE,
B.M_BM_AVERAGE,B.M_CM_AVERAGE,B.M_TOTAL_AVERAGE,
C.JU_BM_AVERAGE,C.JU_CM_AVERAGE,C.JU_TOTAL_AVERAGE,
D.JUL_BM_AVERAGE,D.JUL_CM_AVERAGE,D.JUL_TOTAL_AVERAGE,
E.AU_BM_AVERAGE,E.AU_CM_AVERAGE,E.AU_TOTAL_AVERAGE,
F.S_BM_AVERAGE,F.S_CM_AVERAGE,F.S_TOTAL_AVERAGE
FROM 
a_procuriment A,m_procuriment B,ju_procuriment C,jul_procuriment D,
au_procuriment E,s_procuriment F
WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_procuriment WHERE BCC="VISAKHAPATNAM");





SELECT A.A_TOTAL_AVERAGE+B.M_TOTAL_AVERAGE
+C.JU_TOTAL_AVERAGE
+D.JUL_TOTAL_AVERAGE
+E.AU_TOTAL_AVERAGE
+F.S_TOTAL_AVERAGE
 TOTALAVERAGE
FROM 
a_procuriment A,m_procuriment B,ju_procuriment C,jul_procuriment D,
au_procuriment E,s_procuriment F

WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_procuriment WHERE BCC="VISAKHAPATNAM");



SELECT 
A.A_BM_AVERAGE+B.M_BM_AVERAGE
+C.JU_BM_AVERAGE
+D.JUL_BM_AVERAGE
+E.AU_BM_AVERAGE
+F.S_BM_AVERAGE
 TOTALBMAVERAGE
FROM 
a_procuriment A,m_procuriment B,ju_procuriment C,jul_procuriment D,
au_procuriment E,s_procuriment F
WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_procuriment WHERE BCC="VISAKHAPATNAM");


SELECT A.BCC,A.CENTERCODE,A.CENTERNAME

FROM 
a_procuriment A
WHERE
A.BCC="VISAKHAPATNAM";

SELECT 
A.A_CM_AVERAGE+B.M_CM_AVERAGE
+C.JU_CM_AVERAGE
+D.JUL_CM_AVERAGE
+E.AU_CM_AVERAGE
+F.S_CM_AVERAGE
TOTALCMAVERAGE
FROM 
a_procuriment A,m_procuriment B,ju_procuriment C,jul_procuriment D,
au_procuriment E,s_procuriment F

WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_procuriment WHERE BCC="VISAKHAPATNAM");

//***********************************************************************************************************************************************

SELECT G.O_TOTAL_AVERAGE
+H.N_TOTAL_AVERAGE
+I.D_TOTAL_AVERAGE
+J.JAN_TOTAL_AVERAGE
+K.F_TOTAL_AVERAGE
+L.MAR_TOTAL_AVERAGE TOTALAVERAGE2
FROM o_procuriment G,n_procuriment H,
d_procuriment I,jan_procuriment J,f_procuriment K,mar_procuriment L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM a_procuriment WHERE BCC="VISAKHAPATNAM");

SELECT G.BCC,G.CENTERCODE,G.CENTERNAME,
G.O_BM_AVERAGE,G.O_CM_AVERAGE,G.O_TOTAL_AVERAGE,
H.N_BM_AVERAGE,H.N_CM_AVERAGE,H.N_TOTAL_AVERAGE,
I.D_BM_AVERAGE,I.D_CM_AVERAGE,I.D_TOTAL_AVERAGE,
J.JAN_BM_AVERAGE,J.JAN_CM_AVERAGE,J.JAN_TOTAL_AVERAGE,
K.F_BM_AVERAGE,K.F_CM_AVERAGE,K.F_TOTAL_AVERAGE,
L.MAR_BM_AVERAGE,L.MAR_CM_AVERAGE,L.MAR_TOTAL_AVERAGE
FROM 
o_procuriment G,n_procuriment H,
d_procuriment I,jan_procuriment J,f_procuriment K,mar_procuriment L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM a_procuriment WHERE BCC="VISAKHAPATNAM");

SELECT 

G.O_BM_AVERAGE
+H.N_BM_AVERAGE
+I.D_BM_AVERAGE
+J.JAN_BM_AVERAGE
+K.F_BM_AVERAGE
+L.MAR_BM_AVERAGE TOTALBMAVERAGE2
FROM 
o_procuriment G,n_procuriment H,
d_procuriment I,jan_procuriment J,f_procuriment K,mar_procuriment L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM a_procuriment WHERE BCC="VISAKHAPATNAM");

SELECT 

G.O_CM_AVERAGE
+H.N_CM_AVERAGE
+I.D_CM_AVERAGE
+J.JAN_CM_AVERAGE
+K.F_CM_AVERAGE
+L.MAR_CM_AVERAGE TOTALCMAVERAGE2
FROM 
o_procuriment G,n_procuriment H,
d_procuriment I,jan_procuriment J,f_procuriment K,mar_procuriment L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM a_procuriment WHERE BCC="VISAKHAPATNAM");

//************************************************************************************************************************************************

SELECT SUM(A_BM_AVERAGE)BM_AVG FROM a_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(A_CM_AVERAGE)CM_AVG FROM a_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(A_TOTAL_AVERAGE)TOTAL_AVG FROM a_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(M_BM_AVERAGE)BM_AVG FROM m_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(M_CM_AVERAGE)CM_AVG FROM m_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(M_TOTAL_AVERAGE)TOTAL_AVG FROM m_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(JU_BM_AVERAGE)BM_AVG FROM ju_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(JU_CM_AVERAGE)CM_AVG FROM ju_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(JU_TOTAL_AVERAGE)TOTAL_AVG FROM ju_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(JUL_BM_AVERAGE)BM_AVG FROM jul_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(JUL_CM_AVERAGE)CM_AVG FROM jul_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(JUL_TOTAL_AVERAGE)TOTAL_AVG FROM jul_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(AU_BM_AVERAGE)BM_AVG FROM au_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(AU_CM_AVERAGE)CM_AVG FROM au_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(AU_TOTAL_AVERAGE)TOTAL_AVG FROM au_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(S_BM_AVERAGE)BM_AVG FROM s_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(S_CM_AVERAGE)CM_AVG FROM s_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(S_TOTAL_AVERAGE)TOTAL_AVG FROM s_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(O_BM_AVERAGE)BM_AVG FROM o_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(O_CM_AVERAGE)CM_AVG FROM o_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(O_TOTAL_AVERAGE)TOTAL_AVG FROM o_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(N_BM_AVERAGE)BM_AVG FROM n_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(N_CM_AVERAGE)CM_AVG FROM n_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(N_TOTAL_AVERAGE)TOTAL_AVG FROM n_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(D_BM_AVERAGE)BM_AVG FROM d_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(D_CM_AVERAGE)CM_AVG FROM d_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(D_TOTAL_AVERAGE)TOTAL_AVG FROM d_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(JAN_BM_AVERAGE)BM_AVG FROM jan_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(JAN_CM_AVERAGE)CM_AVG FROM jan_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(JAN_TOTAL_AVERAGE)TOTAL_AVG FROM jan_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(F_BM_AVERAGE)BM_AVG FROM f_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(F_CM_AVERAGE)CM_AVG FROM f_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(F_TOTAL_AVERAGE)TOTAL_AVG FROM f_procuriment WHERE BCC="VISAKHAPATNAM";

SELECT SUM(MAR_BM_AVERAGE)BM_AVG FROM mar_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(MAR_CM_AVERAGE)CM_AVG FROM mar_procuriment WHERE BCC="VISAKHAPATNAM";
SELECT SUM(MAR_TOTAL_AVERAGE)TOTAL_AVG FROM mar_procuriment WHERE BCC="VISAKHAPATNAM";

//***************************************************************************************************************************************************

SELECT TER1_DATEOFTERMENTRY FROM withhelp_ter1 WHERE BCC="VISAKHAPATNAM" ;
SELECT TER2_DATEOFTERMENTRY FROM withhelp_ter2 WHERE BCC="VISAKHAPATNAM" ;
SELECT TER3_DATEOFTERMENTRY FROM withhelp_ter3 WHERE BCC="VISAKHAPATNAM" ;
SELECT TER4_DATEOFTERMENTRY FROM withhelp_ter4 WHERE BCC="VISAKHAPATNAM" ;

SELECT A.BCC,A.CENTERCODE,A.CENTERNAME,
A.TER1_AMOUNT,
B.TER2_AMOUNT,
C.TER3_AMOUNT,
D.TER4_AMOUNT,
A.TER1_AMOUNT+B.TER2_AMOUNT+C.TER3_AMOUNT+D.TER4_AMOUNT TOTAL_TERMAMOUNT
FROM 
withhelp_ter1 A,withhelp_ter2 B,
withhelp_ter3 C,withhelp_ter4 D
WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= ANY(SELECT CENTERNAME FROM withhelp_ter1 WHERE BCC="VISAKHAPATNAM");

SELECT A.BCC,A.CENTERCODE,A.CENTERNAME,A.A_AMOUNT,A.A_ERUVAKA,A.A_PNP,A.A_EXPAMOUNT,A.A_TOTALAMOUNT,
B.M_AMOUNT,B.M_ERUVAKA,B.M_PNP,B.M_EXPAMOUNT,B.M_TOTALAMOUNT,
C.JU_AMOUNT,C.JU_ERUVAKA,C.JU_PNP,C.JU_EXPAMOUNT,C.JU_TOTALAMOUNT,
D.JUL_AMOUNT,D.JUL_ERUVAKA,D.JUL_PNP,D.JUL_EXPAMOUNT,D.JUL_TOTALAMOUNT,
E.AU_AMOUNT,E.AU_ERUVAKA,E.AU_PNP,E.AU_EXPAMOUNT,E.AU_TOTALAMOUNT,
F.S_AMOUNT,F.S_ERUVAKA,F.S_PNP,F.S_EXPAMOUNT,F.S_TOTALAMOUNT
FROM 
a_withhelppriseexp A,m_withhelppriseexp B,ju_withhelppriseexp C,jul_withhelppriseexp D,
au_withhelppriseexp E,s_withhelppriseexp F
WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_withhelppriseexp WHERE BCC="VISAKHAPATNAM");

SELECT G.BCC,G.CENTERCODE,G.CENTERNAME,G.O_AMOUNT,G.O_ERUVAKA,G.O_PNP,G.O_EXPAMOUNT,G.O_TOTALAMOUNT,
H.N_AMOUNT,H.N_ERUVAKA,H.N_PNP,H.N_EXPAMOUNT,H.N_TOTALAMOUNT,
I.D_AMOUNT,I.D_ERUVAKA,I.D_PNP,I.D_EXPAMOUNT,I.D_TOTALAMOUNT,
J.JAN_AMOUNT,J.JAN_ERUVAKA,J.JAN_PNP,J.JAN_EXPAMOUNT,J.JAN_TOTALAMOUNT,
K.F_AMOUNT,K.F_ERUVAKA,K.F_PNP,K.F_EXPAMOUNT,K.F_TOTALAMOUNT,
L.MAR_AMOUNT,L.MAR_ERUVAKA,L.MAR_PNP,L.MAR_EXPAMOUNT,L.MAR_TOTALAMOUNT
FROM 
o_withhelppriseexp G,n_withhelppriseexp H,
d_withhelppriseexp I,jan_withhelppriseexp J,f_withhelppriseexp K,mar_withhelppriseexp L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM o_withhelppriseexp WHERE BCC="VISAKHAPATNAM");


SELECT A.A_AMOUNT+B.M_AMOUNT
+C.JU_AMOUNT
+D.JUL_AMOUNT
+E.AU_AMOUNT
+F.S_AMOUNT
 TOTALAMOUNTWHP
FROM 
a_withhelppriseexp A,m_withhelppriseexp B,ju_withhelppriseexp C,jul_withhelppriseexp D,
au_withhelppriseexp E,s_withhelppriseexp F

WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_withhelppriseexp WHERE BCC="VISAKHAPATNAM");


SELECT A.A_ERUVAKA+B.M_ERUVAKA
+C.JU_ERUVAKA
+D.JUL_ERUVAKA
+E.AU_ERUVAKA
+F.S_ERUVAKA
 TOTALERUVAKAWHP
FROM 
a_withhelppriseexp A,m_withhelppriseexp B,ju_withhelppriseexp C,jul_withhelppriseexp D,
au_withhelppriseexp E,s_withhelppriseexp F

WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_withhelppriseexp WHERE BCC="VISAKHAPATNAM");

SELECT A.A_PNP+B.M_PNP
+C.JU_PNP
+D.JUL_PNP
+E.AU_PNP
+F.S_PNP
 TOTALPNPWHP
FROM 
a_withhelppriseexp A,m_withhelppriseexp B,ju_withhelppriseexp C,jul_withhelppriseexp D,
au_withhelppriseexp E,s_withhelppriseexp F

WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_withhelppriseexp WHERE BCC="VISAKHAPATNAM");

SELECT A.A_EXPAMOUNT+B.M_EXPAMOUNT
+C.JU_EXPAMOUNT
+D.JUL_EXPAMOUNT
+E.AU_EXPAMOUNT
+F.S_EXPAMOUNT
 TOTALEXPAMOUNTWHP
FROM 
a_withhelppriseexp A,m_withhelppriseexp B,ju_withhelppriseexp C,jul_withhelppriseexp D,
au_withhelppriseexp E,s_withhelppriseexp F

WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_withhelppriseexp WHERE BCC="VISAKHAPATNAM");

SELECT A.A_TOTALAMOUNT+B.M_TOTALAMOUNT
+C.JU_TOTALAMOUNT
+D.JUL_TOTALAMOUNT
+E.AU_TOTALAMOUNT
+F.S_TOTALAMOUNT
 TOTALTOTALAMOUNT
FROM 
a_withhelppriseexp A,m_withhelppriseexp B,ju_withhelppriseexp C,jul_withhelppriseexp D,
au_withhelppriseexp E,s_withhelppriseexp F

WHERE A.CENTERNAME= B.CENTERNAME AND B.CENTERNAME= C.CENTERNAME AND C.CENTERNAME= D.CENTERNAME AND D.CENTERNAME= E.CENTERNAME AND E.CENTERNAME= F.CENTERNAME AND 
F.CENTERNAME = ANY(SELECT CENTERNAME FROM a_withhelppriseexp WHERE BCC="VISAKHAPATNAM");

SELECT G.O_AMOUNT
+H.N_AMOUNT
+I.D_AMOUNT
+J.JAN_AMOUNT
+K.F_AMOUNT
+L.MAR_AMOUNT TOTALAMOUNTWHP2
FROM o_withhelppriseexp G,n_withhelppriseexp H,
d_withhelppriseexp I,jan_withhelppriseexp J,f_withhelppriseexp K,mar_withhelppriseexp L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM o_withhelppriseexp WHERE BCC="VISAKHAPATNAM");


SELECT G.O_ERUVAKA
+H.N_ERUVAKA
+I.D_ERUVAKA
+J.JAN_ERUVAKA
+K.F_ERUVAKA
+L.MAR_ERUVAKA TOTALERUVAKAWHP2
FROM o_withhelppriseexp G,n_withhelppriseexp H,
d_withhelppriseexp I,jan_withhelppriseexp J,f_withhelppriseexp K,mar_withhelppriseexp L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM o_withhelppriseexp WHERE BCC="VISAKHAPATNAM");


SELECT G.O_PNP
+H.N_PNP
+I.D_PNP
+J.JAN_PNP
+K.F_PNP
+L.MAR_PNP TOTALPNPWHP2
FROM o_withhelppriseexp G,n_withhelppriseexp H,
d_withhelppriseexp I,jan_withhelppriseexp J,f_withhelppriseexp K,mar_withhelppriseexp L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM o_withhelppriseexp WHERE BCC="VISAKHAPATNAM");

SELECT G.O_EXPAMOUNT
+H.N_EXPAMOUNT
+I.D_EXPAMOUNT
+J.JAN_EXPAMOUNT
+K.F_EXPAMOUNT
+L.MAR_EXPAMOUNT TOTALEXPAMOUNTWHP2
FROM o_withhelppriseexp G,n_withhelppriseexp H,
d_withhelppriseexp I,jan_withhelppriseexp J,f_withhelppriseexp K,mar_withhelppriseexp L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM o_withhelppriseexp WHERE BCC="VISAKHAPATNAM");


SELECT G.O_TOTALAMOUNT
+H.N_TOTALAMOUNT
+I.D_TOTALAMOUNT
+J.JAN_TOTALAMOUNT
+K.F_TOTALAMOUNT
+L.MAR_TOTALAMOUNT TOTALTOTALAMOUNTWHP2
FROM o_withhelppriseexp G,n_withhelppriseexp H,
d_withhelppriseexp I,jan_withhelppriseexp J,f_withhelppriseexp K,mar_withhelppriseexp L
WHERE G.CENTERNAME= H.CENTERNAME AND H.CENTERNAME= I.CENTERNAME AND I.CENTERNAME= J.CENTERNAME AND J.CENTERNAME= K.CENTERNAME AND K.CENTERNAME= L.CENTERNAME AND 
L.CENTERNAME = ANY(SELECT CENTERNAME FROM o_withhelppriseexp WHERE BCC="VISAKHAPATNAM");


